#file to bump version automatically by calling this bash script treeder/bump/master/gitbump.sh
#bumps version on every main branch push
name: Bump version in git

on:
  pull_request:
    types: [reopened]
jobs:
  build-and-deploy:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version
      run: |
        git config --global user.email "github+actions@gmail.com"
        git config --global user.name "Actions"
        git fetch --tags
        wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
 
