name: Greetings

on: 
  #[pull_request, issues]
  deployment
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'So you umm made your first issue... nice....'
        pr-message: 'Message that will be displayed on users first pull request'
